# Generated by Django 3.1.4 on 2021-04-23 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250)),
                ('amount', models.FloatField(max_length=10)),
                ('user_name', models.CharField(max_length=250)),
                ('billing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('category_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=10)),
                ('gym', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('ac', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField()),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.roomcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField()),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.bill')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
